bleopt complete_auto_delay=100
ble-face syntax_error=fg=203
ble-face auto_complete=fg=242
ble-face command_file=fg=003
ble-face command_builtin=fg=003
ble-face command_alias=fg=003
ble-face filename_directory=fg=003
ble-face filename_other=fg=003
bleopt exec_errexit_mark=
